sudo: required

services:
  - docker

before_install:
  - docker build -t eden docker
  - docker run eden /bin/bash "cd /opt/EDeN"

script:
  - flake8 . --exclude=.venv --ignore=E501
  # run nose with doctests
  # excludes files with missing or broken dependencies
  - nosetests --with-doctest -I selector.py -I embedding.py -I obabel.py
